import { IMAGES } from './image-config'

export const GALLERY_DATA = [
  {
    id: 'titi-simagre',
    image: IMAGES.projects[0].main,
    detailImages: IMAGES.projects[0].details,
    title: 'Titi Simagre',
    titleId: 'Titi Simagre',
    category: 'Titi Mentawai',
    categoryId: 'Titi Mentawai',
    placement: 'Full Body',
    placementId: 'Seluruh Tubuh',
    duration: 'Multiple Sessions',
    durationId: 'Beberapa Sesi',
    meaning: 'Simagre (Soul), Identity, Spiritual Protection',
    meaningId: 'Simagre (Jiwa), Identitas, Perlindungan Spiritual',
    story: 'In Mentawai belief, the simagre — the soul residing within the body — must be adorned so it can be recognized by ancestral spirits after death. Titi are not merely marks on skin; they are understood to clothe the simagre in beauty and protection. This is not metaphor. It is how the Mentawai people have understood tattooing, as documented by ethnographers and anthropologists who studied Mentawai society.',
    storyId: 'Dalam kepercayaan Mentawai, simagre — jiwa yang berdiam dalam tubuh — harus dihias agar dapat dikenali oleh roh leluhur setelah kematian. Titi bukan sekadar tanda di kulit; titi dipahami sebagai pakaian bagi simagre dalam keindahan dan perlindungan. Ini bukan metafora. Inilah cara masyarakat Mentawai memahami tato, sebagaimana didokumentasikan oleh para etnografer dan antropolog yang mempelajari masyarakat Mentawai.',
    fallbackPattern: 'protection' as const,
    featured: true,
  },
  {
    id: 'arat-sabulungan',
    image: IMAGES.projects[1].main,
    detailImages: IMAGES.projects[1].details,
    title: 'Arat Sabulungan',
    titleId: 'Arat Sabulungan',
    category: 'Titi Mentawai',
    categoryId: 'Titi Mentawai',
    placement: 'Chest & Arms',
    placementId: 'Dada & Lengan',
    duration: '2–3 Sessions',
    durationId: '2–3 Sesi',
    meaning: 'Ancestral Law, Spiritual Balance, Way of Life',
    meaningId: 'Hukum Leluhur, Keseimbangan Spiritual, Jalan Hidup',
    story: 'Arat Sabulungan — the Way of the Leaf Bundle — is the traditional animist belief system of the Mentawai people. Leaf bundles, called sabulungan, are sacred objects tied to homes and trees; they connect the living to the spirit world. Receiving a titi was traditionally an act of living within this system: honoring the body, the forest, and the order passed down from the ancestors.',
    storyId: 'Arat Sabulungan — Jalan Ikat Daun — adalah sistem kepercayaan animis tradisional masyarakat Mentawai. Ikat daun, disebut sabulungan, adalah benda sakral yang diikat pada rumah dan pohon; mereka menghubungkan yang hidup dengan dunia roh. Mendapatkan titi secara tradisional adalah tindakan hidup sesuai sistem ini: menghormati tubuh, hutan, dan tatanan yang diturunkan dari leluhur.',
    fallbackPattern: 'warrior' as const,
    featured: false,
  },
  {
    id: 'puliaijat',
    image: IMAGES.projects[2].main,
    detailImages: IMAGES.projects[2].details,
    title: 'Puliaijat',
    titleId: 'Puliaijat',
    category: 'Titi Mentawai',
    categoryId: 'Titi Mentawai',
    placement: 'Back',
    placementId: 'Punggung',
    duration: '3–4 Sessions',
    durationId: '3–4 Sesi',
    meaning: 'Ceremony, Community, Rite of Passage',
    meaningId: 'Upacara, Komunitas, Ritual Peralihan',
    story: 'Puliaijat are the ceremonial feasts of the Mentawai people — communal events in which families gather to give thanks, mark life transitions, and maintain balance with the spirit world. Traditionally, receiving a titi was embedded within this ceremonial context: witnessed by the community, guided by the sikerei, and offered as acknowledgment to the ancestral world. A titi made in puliaijat was never a private act.',
    storyId: 'Puliaijat adalah pesta upacara masyarakat Mentawai — peristiwa komunal di mana keluarga berkumpul untuk bersyukur, menandai peralihan hidup, dan menjaga keseimbangan dengan dunia roh. Secara tradisional, mendapatkan titi tertanam dalam konteks upacara ini: disaksikan oleh komunitas, dipandu oleh sikerei, dan dipersembahkan sebagai pengakuan kepada dunia leluhur. Titi yang dibuat dalam puliaijat tidak pernah menjadi tindakan pribadi.',
    fallbackPattern: 'lineage' as const,
    featured: false,
  },
  {
    id: 'uma',
    image: IMAGES.projects[3].main,
    detailImages: IMAGES.projects[3].details,
    title: 'Uma',
    titleId: 'Uma',
    category: 'Titi Mentawai',
    categoryId: 'Titi Mentawai',
    placement: 'Shoulders & Upper Arms',
    placementId: 'Bahu & Lengan Atas',
    duration: '2 Sessions',
    durationId: '2 Sesi',
    meaning: 'Clan, Communal Identity, Belonging',
    meaningId: 'Klan, Identitas Komunal, Rasa Memiliki',
    story: 'The uma — the traditional Mentawai communal longhouse — is the foundation of social life. Extended families live, gather, and conduct ceremonies together under one uma roof. Tattoo patterns in traditional Mentawai society were connected to the wearer\'s uma: marking their place within a specific clan and their responsibilities to that community. To carry these marks is to carry your people.',
    storyId: 'Uma — rumah panjang komunal tradisional Mentawai — adalah fondasi kehidupan sosial. Keluarga besar hidup, berkumpul, dan melaksanakan upacara bersama di bawah satu atap uma. Pola tato dalam masyarakat Mentawai tradisional berkaitan dengan uma si pemakai: menandai tempat mereka dalam klan tertentu dan tanggung jawab mereka kepada komunitas itu. Membawa tanda-tanda ini berarti membawa serta masyarakatmu.',
    fallbackPattern: 'river' as const,
    featured: false,
  },
  {
    id: 'sikerei',
    image: IMAGES.projects[4].main,
    detailImages: IMAGES.projects[4].details,
    title: 'Sikerei',
    titleId: 'Sikerei',
    category: 'Titi Mentawai',
    categoryId: 'Titi Mentawai',
    placement: 'Full Upper Body',
    placementId: 'Tubuh Atas Penuh',
    duration: '4–5 Sessions',
    durationId: '4–5 Sesi',
    meaning: 'Healing, Spiritual Knowledge, Sacred Responsibility',
    meaningId: 'Penyembuhan, Pengetahuan Spiritual, Tanggung Jawab Sakral',
    story: 'The sikerei is the traditional Mentawai healer and mediator between the human world and the spirit world. Their bodies are among the most extensively tattooed in Mentawai society — each mark reflects their accumulated spiritual knowledge, their protective role within the community, and their relationship to the ancestral world. The sikerei does not choose to be heavily tattooed; the marks come with the path.',
    storyId: 'Sikerei adalah penyembuh tradisional Mentawai dan mediator antara dunia manusia dan dunia roh. Tubuh mereka termasuk yang paling banyak ditato dalam masyarakat Mentawai — setiap tanda mencerminkan pengetahuan spiritual yang terkumpul, peran perlindungan mereka dalam komunitas, dan hubungan mereka dengan dunia leluhur. Sikerei tidak memilih untuk ditato secara luas; tanda-tanda datang seiring dengan jalan yang dipilih.',
    fallbackPattern: 'spirit' as const,
    featured: false,
  },
  {
    id: 'rereiket',
    image: IMAGES.projects[5].main,
    detailImages: IMAGES.projects[5].details,
    title: 'Rereiket',
    titleId: 'Rereiket',
    category: 'Titi Mentawai',
    categoryId: 'Titi Mentawai',
    placement: 'Legs & Feet',
    placementId: 'Kaki & Telapak Kaki',
    duration: '2 Sessions',
    durationId: '2 Sesi',
    meaning: 'Land, Living Tradition, Roots',
    meaningId: 'Tanah, Tradisi Hidup, Akar',
    story: 'The Rereiket area of Siberut island — the largest of the four Mentawai Islands — is among the last places where traditional Mentawai life continues in a relatively unbroken form. Siberut has been a UNESCO Biosphere Reserve since 1981. The patterns carried from this land represent a direct, living connection to ancestral Mentawai culture. Rereiket is not a name given to tradition; it is where tradition still breathes.',
    storyId: 'Kawasan Rereiket di Pulau Siberut — yang terbesar dari empat Kepulauan Mentawai — adalah salah satu tempat terakhir di mana kehidupan Mentawai tradisional masih berlanjut dalam bentuk yang relatif tidak terputus. Siberut telah menjadi Cagar Biosfer UNESCO sejak 1981. Pola yang dibawa dari tanah ini merupakan koneksi langsung dan hidup dengan budaya Mentawai leluhur. Rereiket bukan nama yang diberikan pada tradisi; ini adalah tempat di mana tradisi masih bernapas.',
    fallbackPattern: 'forest' as const,
    featured: false,
  },
]
