import { IMAGES } from './image-config'

export const GALLERY_DATA = [
  {
    id: 'protection',
    image: IMAGES.projects[0].main,
    detailImages: IMAGES.projects[0].details,
    title: 'Protection',
    titleId: 'Perlindungan',
    category: 'Full Back Piece',
    categoryId: 'Punggung Penuh',
    placement: 'Full Back',
    placementId: 'Punggung Penuh',
    duration: '4 Sessions',
    meaning: 'Protection, Strength, Guidance',
    meaningId: 'Perlindungan, Kekuatan, Bimbingan',
    story: 'This piece was created for a warrior of the sea, who carries the responsibility of his people. The pattern represents the shield that guards his body, mind, and spirit on every journey.',
    storyId: 'Karya ini dibuat untuk seorang pejuang laut, yang menanggung tanggung jawab rakyatnya. Pola ini mewakili perisai yang menjaga tubuh, pikiran, dan jiwa dalam setiap perjalanan.',
    fallbackPattern: 'protection' as const,
    featured: true,
  },
  {
    id: 'courage',
    image: IMAGES.projects[1].main,
    detailImages: IMAGES.projects[1].details,
    title: 'Courage',
    titleId: 'Keberanian',
    category: 'Arm Piece',
    categoryId: 'Lengan',
    placement: 'Right Arm',
    placementId: 'Lengan Kanan',
    duration: '2 Sessions',
    meaning: 'Bravery, Ancestral Connection',
    meaningId: 'Keberanian, Koneksi Leluhur',
    story: 'Drawn from the warrior markings of the Rereiket tribe. Each line tells of battles fought not with weapons, but with wisdom and perseverance through hardship.',
    storyId: 'Diambil dari tanda pejuang suku Rereiket. Setiap garis menceritakan pertempuran bukan dengan senjata, tetapi dengan kebijaksanaan dan ketekunan.',
    fallbackPattern: 'warrior' as const,
    featured: false,
  },
  {
    id: 'heritage',
    image: IMAGES.projects[2].main,
    detailImages: IMAGES.projects[2].details,
    title: 'Heritage',
    titleId: 'Warisan',
    category: 'Chest Piece',
    categoryId: 'Dada',
    placement: 'Chest',
    placementId: 'Dada',
    duration: '3 Sessions',
    meaning: 'Lineage, Identity, Honor',
    meaningId: 'Silsilah, Identitas, Kehormatan',
    story: "A tribute to the client's grandmother, a keeper of traditional Mentawai weaving patterns. The motifs mirror her work, now carried permanently on his chest.",
    storyId: 'Penghormatan kepada nenek klien, penjaga pola tenun Mentawai. Motifnya mencerminkan karyanya, kini terbawa abadi di dadanya.',
    fallbackPattern: 'lineage' as const,
    featured: false,
  },
  {
    id: 'journey',
    image: IMAGES.projects[3].main,
    detailImages: IMAGES.projects[3].details,
    title: 'Journey',
    titleId: 'Perjalanan',
    category: 'Leg Piece',
    categoryId: 'Kaki',
    placement: 'Left Leg',
    placementId: 'Kaki Kiri',
    duration: '2 Sessions',
    meaning: 'Path, Direction, Purpose',
    meaningId: 'Jalur, Arah, Tujuan',
    story: 'Created at a turning point in life. The spiraling pattern represents the river — always moving, always finding its way to the sea.',
    storyId: 'Dibuat di titik balik kehidupan. Pola spiral mewakili sungai — selalu bergerak, selalu menemukan jalannya ke laut.',
    fallbackPattern: 'river' as const,
    featured: false,
  },
  {
    id: 'spirit',
    image: IMAGES.projects[4].main,
    detailImages: IMAGES.projects[4].details,
    title: 'Spirit',
    titleId: 'Roh',
    category: 'Shoulder Piece',
    categoryId: 'Bahu',
    placement: 'Right Shoulder',
    placementId: 'Bahu Kanan',
    duration: '1 Session',
    meaning: 'Spiritual Protection, Balance',
    meaningId: 'Perlindungan Spiritual, Keseimbangan',
    story: 'Based on the sacred titi patterns worn by sikerei shamans during healing ceremonies. A mark of spiritual guardian.',
    storyId: 'Berdasarkan pola titi sakral yang dikenakan dukun sikerei dalam upacara penyembuhan. Tanda pelindung spiritual.',
    fallbackPattern: 'spirit' as const,
    featured: false,
  },
  {
    id: 'roots',
    image: IMAGES.projects[5].main,
    detailImages: IMAGES.projects[5].details,
    title: 'Roots',
    titleId: 'Akar',
    category: 'Back Piece',
    categoryId: 'Punggung',
    placement: 'Upper Back',
    placementId: 'Punggung Atas',
    duration: '3 Sessions',
    meaning: 'Origin, Family, Earth',
    meaningId: 'Asal, Keluarga, Bumi',
    story: 'The sago palm — lifeline of the Mentawai people — forms the spine of this piece. It speaks of belonging to a place and a people.',
    storyId: 'Pohon sagu — penghidupan masyarakat Mentawai — membentuk tulang punggung karya ini. Berbicara tentang rasa memiliki.',
    fallbackPattern: 'forest' as const,
    featured: false,
  },
]
